Les14/Models/Binding/MultipleCheckboxViewModel.cs
using System.Collections.Generic;

namespace Les14.Models.Binding
{
    public class MultipleCheckboxViewModel
    {
        public class Checkbox
        {
            public bool Selected { get; set; }
            public string ID { get; set; }
            public string Text { get; set; }
        }

        public List<Checkbox> Checkboxen { get; set; } = new List<Checkbox>();
    }
}

Les14/Models/EntityFramework/KeyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Les14.Models.EntityFramework
{
    public class KeyViewModel
    {
        /// <summary>
        /// Bevat de max value van de kolom + 1.
        /// Dit wordt als suggestie gegeven voor een nieuwe key in de NoAutoGeneratedKey tabel.
        /// </summary>
        public int KeySuggestionForNoAutoGeneratedKey { get; set; }
    }
}

Les14/Models/ErrorViewModel.cs
using System;

namespace Les14.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Les14/Models/Kendo/GridViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Les14.Models.Kendo
{
    public class GridViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Les14/Controllers/BindingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Les14.Models.Binding;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Les14.Controllers
{
    public class BindingController : Controller
    {
        #region Multiple checkbox
        [HttpGet]
        public IActionResult MultipleCheckboxViaFormPost()
        {
            var model = CreateViewModelWithDummyData();
            return View(model);
        }

        [HttpPost]
        public IActionResult MultipleCheckboxViaFormPost(MultipleCheckboxViewModel model)
        {
            var aangvinkteIds = model.Checkboxen.Where(c => c.Selected).Select(c => c.ID).ToList();
            return Json($"Jij vinkte {string.Join(',',aangvinkteIds)} aan");
        }

        public IActionResult MultipleCheckboxViaAjaxPost()
        {
            var model = CreateViewModelWithDummyData();
            return View(model);
        }

        [HttpPost]
        public IActionResult MultipleCheckboxViaAjaxPost(MultipleCheckboxViewModel model)
        {
            var aangvinkteIds = model.Checkboxen.Where(c => c.Selected).Select(c => c.ID).ToList();
            return Json($"Jij vinkte {string.Join(',', aangvinkteIds)} aan");
        }

        private MultipleCheckboxViewModel CreateViewModelWithDummyData()
        {
            MultipleCheckboxViewModel model = new MultipleCheckboxViewModel();
            foreach (var id in new string[] { "A", "B", "C", "D", "E" })
            {
                model.Checkboxen.Add(new MultipleCheckboxViewModel.Checkbox()
                {
                    Selected = false,
                    ID = id,
                    Text = $"Hier wat uitleg over {id}"
                });
            }
            return model;
        }
        #endregion
    }
}

Les14/Controllers/EntityFrameworkController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Les14.Domain;
using Les14.Domain.Models;
using Les14.Models.EntityFramework;
using Microsoft.AspNetCore.Mvc;

namespace Les14.Controllers
{
    public class EntityFrameworkController : Controller
    {
        public IActionResult Include()
        {
            CreateInitialDataIfNecessary();

            RelationManager mgr = new RelationManager();
            Parent p = mgr.GetParent(1, true);

            return View(p);
        }

        private void CreateInitialDataIfNecessary()
        {
            RelationManager mgr = new RelationManager();
            if (mgr.GetParent(1, false) == null)
            {
                mgr.AddParent(new Parent()
                {
                    Children = new List<Child>
                    {
                        new Child() { ParentID = 1 },
                        new Child() { ParentID = 1 }, 
                        new Child() { ParentID = 1 }
                    }
                });
            }
        }

        public IActionResult IdentityColumn()
        {
            KeyManager mgr = new KeyManager();
            KeyViewModel model = new KeyViewModel()
            {
                KeySuggestionForNoAutoGeneratedKey = mgr.GetMaxKey() + 1
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult IdentityColumn(KeyViewModel model)
        {
            // model bevat nu de suggestie (of een key die door de gebruiker zelf werd gekozen).
            KeyManager mgr = new KeyManager();

            AutoGeneratedKey agkEntity = new AutoGeneratedKey()
            {
                Id = 0 // eigenlijk overbodig, want default value van een int is 0
            };
            NoAutoGeneratedKey nagkEntity = new NoAutoGeneratedKey()
            {
                Id = model.KeySuggestionForNoAutoGeneratedKey
            };

            mgr.AddAutoGeneratedKey(agkEntity);
            mgr.AddNoAutoGeneratedKey(nagkEntity);

            return Json($"Created entities. Auto generated key: {agkEntity.Id}, No auto generated key: {nagkEntity.Id}.");
        }
    }
}

Les14/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Les14.Models;

namespace Les14.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Les14/Controllers/KendoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Les14.Models.Kendo;
using Microsoft.AspNetCore.Mvc;

namespace Les14.Controllers
{
    public class KendoController : Controller
    {
        public IActionResult Grid()
        {
            return View();
        }

        public IActionResult Grid_Read(DataSourceRequest request)
        {
            List<GridViewModel> model = new List<GridViewModel>();
            model.Add(new GridViewModel()
            {
                ID = 1,
                Name = "Test",
                Description = "Dit is een test"
            });
            return Json(model.ToDataSourceResult(request));
        }
    }
}

Les14/Controllers/PartialViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Les14.Controllers
{
    public class PartialViewController : Controller
    {
        public IActionResult ARoomWithAView()
        {
            return View();
        }
    }
}

Les14/Controllers/RedirectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Les14.Controllers
{
    public class RedirectController : Controller
    {
        public IActionResult RedirectServerSide()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RedirectServerSide_Post()
        {
            return Redirect("https://hackernoon.com/15-jokes-only-programmers-will-get-b42873eba509");
        }

        public IActionResult RedirectClientSide()
        {
            return View();
        }
    }
}

Les14/Views/Binding/MultipleCheckbox.cshtml
@model Les14.Models.Binding.MultipleCheckboxViewModel

@{
    ViewData["Title"] = "Multiple checkbox";
}

<h2>Multiple checkboxen</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="MultipleCheckbox">
            
            @for (int i = 0; i < Model.Checkboxen.Count(); i++)
            {
                <label><input type="checkbox" asp-for="@Model.Checkboxen[i].Selected" />@Model.Checkboxen[i].Text</label>
                <input type="hidden" asp-for="@Model.Checkboxen[i].ID"/>
                <br />
            }

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Les14/Views/Binding/MultipleCheckboxViaAjaxPost.cshtml
@model Les14.Models.Binding.MultipleCheckboxViewModel

@{
    ViewData["Title"] = "Multiple checkbox via AJAX POST";
}

<h2>Multiple checkbox via AJAX POST</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="MultipleCheckboxViaAjaxPost">

            @foreach (var item in Model.Checkboxen)
            {
                <label><input type="checkbox" name="@item.ID" />@item.Text</label>
                <br />
            }

            <div class="form-group">
                <input id="submit" type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div class="row">
    <p><strong>Server feedback:</strong> <em><span id="feedback"></span></em></p>
</div>

<script>
    // OPGELET: dit moet in principe naar een apart .js bestand!
    document.getElementById("submit").addEventListener("click", function (event) {
        try {
            // We maken een JavaScript object dat 1-1 mapt met de specificatie van MultipleCheckboxViewModel.
            var model = {
                checkboxen: []
            };

            // Ophalen van alle inputs van type checkbox.
            var checkboxInputs = document.querySelectorAll("input[type='checkbox']");
            checkboxInputs.forEach(cb => {
                model.checkboxen.push({
                    id: cb.getAttribute("name"),
                    selected: cb.checked
                });
            });

            // Ajax call
            $.post("/binding/MultipleCheckboxViaAjaxPost", model, function (response) {
                document.getElementById("feedback").innerText = response;
            });
        } finally {
            // Dit zorgt ervoor dat er geen form submit gebeurt.
            // Zo zal er ook geen page refresh plaatsvinden.
            event.preventDefault();
        }
    });
</script>

<div>
    <a asp-action="Index" asp-controller="Home">Back to home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Les14/Views/Binding/MultipleCheckboxViaFormPost.cshtml
@model Les14.Models.Binding.MultipleCheckboxViewModel

@{
    ViewData["Title"] = "Multiple checkbox via form POST";
}

<h2>Multiple checkbox via form POST</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="MultipleCheckboxViaFormPost">
            
            @for (int i = 0; i < Model.Checkboxen.Count(); i++)
            {
                <label><input type="checkbox" asp-for="@Model.Checkboxen[i].Selected" />@Model.Checkboxen[i].Text</label>
                <input type="hidden" asp-for="@Model.Checkboxen[i].ID"/>
                <br />
            }

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Back to home</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Les14/Views/EntityFramework/IdentityColumn.cshtml
@model Les14.Models.EntityFramework.KeyViewModel

@{
    ViewData["Title"] = "Identity column";
}

<h2>Identity column</h2>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="IdentityColumn">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="KeySuggestionForNoAutoGeneratedKey" class="control-label"></label>
                <input asp-for="KeySuggestionForNoAutoGeneratedKey" class="form-control" />
                <span asp-validation-for="KeySuggestionForNoAutoGeneratedKey" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create entities" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" asp-controller="Home">Back to home</a>
</div>

Les14/Views/EntityFramework/Include.cshtml
@model Les14.Domain.Parent

@{
    ViewData["Title"] = "Include";
}

<h2>Include</h2>

<div>
    <h3>Parent @Model.Id heeft deze child records:</h3>
    <table>
        <tr><td>ID</td></tr>
        @foreach (var child in Model.Children)
        {
            <tr><td>@child.Id</td></tr>
        }
    </table>
</div>
<div>
    <a asp-action="Index" asp-controller="Home">Back to home</a>
</div>

Les14/Views/EntityFramework/ParentChild.cshtml
@model Les14.Domain.Parent

@{
    ViewData["Title"] = "ParentChild";
}

<h2>ParentChild</h2>

<div>
    <h3>Parent @Model.Id heeft deze child records:</h3>
    <table>
        <tr><td>ID</td></tr>
        @foreach (var child in Model.Children)
        {
            <tr><td>@child.Id</td></tr>
        }
    </table>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

Les14/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-4">
        <h2>Binding</h2>
        <ul>
            <li>@Html.ActionLink("Multiple checkboxes (via form POST)", "MultipleCheckboxViaFormPost", "Binding")</li>
            <li>@Html.ActionLink("Multiple checkboxes (via AJAX POST)", "MultipleCheckboxViaAjaxPost", "Binding")</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Redirect</h2>
        <ul>
            <li>@Html.ActionLink("Redirect (server-side)", "RedirectServerSide", "Redirect")</li>
            <li>@Html.ActionLink("Redirect (client-side)", "RedirectClientSide", "Redirect")</li>
        </ul>
    </div>
    <div class="col-md-4">
        <h2>Widget frameworks</h2>
        <ul>
            <li>@Html.ActionLink("Grid (Kendo UI)", "Grid", "Kendo")</li>
        </ul>
    </div>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Entity Framework</h2>
        <ul>
            <li>@Html.ActionLink("Include (vb. parent-child)", "Include", "EntityFramework")</li>
            <li>@Html.ActionLink("Identity column (vb. auto generated key)", "IdentityColumn", "EntityFramework")</li>
        </ul>
    </div>
    <div class="col-md-4">
    </div>
    <div class="col-md-4">
    </div>
</div>

Les14/Views/Kendo/Grid.cshtml
@model Les14.Models.Kendo.GridViewModel

@{
    ViewData["Title"] = "Kendo voorbeelden";
}

<h2>Kendo Grid voorbeeld</h2>
<p>De gegevens worden asynchroon opgehaald via een Grid_Read action op de KendoController.</p>

@(Html.Kendo().Grid<Les14.Models.Kendo.GridViewModel>()
            .Name("grid")
            .Columns(columns =>
            {
                columns.Bound(c => c.ID);
                columns.Bound(c => c.Name);
                columns.Bound(c => c.Description);
            })
            .HtmlAttributes(new { style = "height: 550px;" })
            .Scrollable()
            .Groupable()
            .Sortable()
            .Pageable(pageable => pageable
                .Refresh(true)
                .PageSizes(true)
                .ButtonCount(5))
            .DataSource(dataSource => dataSource
                .Ajax()
                .Read(read => read.Action("Grid_Read", "Kendo"))
                .PageSize(20)
            )
)

Les14/Views/PartialView/ARoomWithAView.cshtml
@{
    ViewData["Title"] = "ARoomWithAView";
}

<h2>A room with a view</h2>

Les14/Views/Redirect/RedirectClientSide.cshtml
@{
    ViewData["Title"] = "Redirect client-side";
}

<h2>Redirect client-side</h2>

<p></p>
<p>Click button to redirect in JavaScript.</p>
<button id="redirect">Redirect</button>

<script>
    // OPGELET: dit moet in principe naar een apart .js bestand!
    document.getElementById("redirect").addEventListener("click", function (event) {
        window.location = "http://geek-and-poke.com/geekandpoke/2013/7/22/future-proof-your-data-model";
    });
</script>

Les14/Views/Redirect/RedirectServerSide.cshtml
@{
    ViewData["Title"] = "Redirect server-side";
}

<h2>Redirect server-side</h2>
<form asp-action="RedirectServerSide_Post" method="post">
    <p>Click button to submit form and perform a server-side redirect.</p>
    <input type="submit" name="submit" value="Submit" />
</form>

Les14/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Softwareontwikkeling in .NET - Demo's en voorbeelden</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <script src="~/bundle.js" runat="server"></script>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Demo's en voorbeelden</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Softwareontwikkeling in .NET - Demo's en voorbeelden</p>
        </footer>
    </div>

    <environment include="Development">
        @*<script src="~/lib/jquery/dist/jquery.js"></script>*@
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        @*<script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>*@
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>